{% set name = "rod" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rod-{{ version }}.tar.gz
  sha256: ec2e9f606c036a67f77491c7247fc8de69a7393d51c52b117083215bd0cc77cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - wheel
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - trimesh
    - resolve-robotics-uri-py
    - python >=3.10
    - coloredlogs
    - gz-tools2
    - libsdformat13
    - mashumaro
    - numpy
    - packaging
    - scipy
    - xmltodict

test:
  imports:
    - rod
  commands:
    - pip check
    - pytest -vv --pyargs rod tests/
  source_files:
    - tests/*
  requires:
    - git
    - idyntree >=12.4
    - pip
    - pytest
    - robot_descriptions

about:
  home: https://github.com/ami-iit/rod
  summary: The ultimate Python tool for RObot Descriptions processing.
  dev_url: https://github.com/ami-iit/rod
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - diegoferigo
    - traversaro
    - flferretti
