{% set name = "rod" %}
{% set version = "0.3.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rod-{{ version }}.tar.gz
  sha256: 8f4028a56264f35907d0fdfbf9f36f6131fd35a8e721f1301b91892c9622c5e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - wheel
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - trimesh
    - resolve-robotics-uri-py
    - python >={{ python_min }}
    - coloredlogs
    - gz-tools2
    - libsdformat13
    - mashumaro
    - numpy
    - packaging
    - scipy
    - xmltodict

test:
  imports:
    - rod
  commands:
    - pip check
    - pytest -vv --pyargs rod tests/
  source_files:
    - tests/*
  requires:
    - python {{ python_min }}
    - git
    - idyntree >=12.4
    - pip
    - pytest
    - robot_descriptions

about:
  home: https://github.com/ami-iit/rod
  summary: The ultimate Python tool for RObot Descriptions processing.
  dev_url: https://github.com/ami-iit/rod
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - diegoferigo
    - traversaro
    - flferretti
