schema_version: 1

context:
  name: rod
  version: "0.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/rod-${{ version }}.tar.gz
  sha256: 2b33adf32551578bcfd17759f650dde33693a3d70879df9094ea7654589395ea

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - trimesh
    - resolve-robotics-uri-py
    - python >=${{ python_min }}
    - coloredlogs
    - gz-tools
    - libsdformat
    - mashumaro
    - numpy
    - packaging
    - scipy
    - xmltodict

tests:
  - python:
      imports:
        - rod
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests/*
    requirements:
      run:
        - python ${{ python_min }}.*
        - git
        - idyntree >=12.4
        - pip
        - pytest
        - robot_descriptions
    script:
      - pytest -vv --pyargs rod tests/

about:
  summary: The ultimate Python tool for RObot Descriptions processing.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/ami-iit/rod
  repository: https://github.com/ami-iit/rod

extra:
  recipe-maintainers:
    - diegoferigo
    - traversaro
    - flferretti
